on:
  push:
    branches: [ main ]
  schedule:
    - cron: 37 4 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    - uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tags: alexpdp7/rust-wasm-pack-rollup:latest
        push: true
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
